export const mockData = [{
    orgId: '12123',
    caheorgId: '12123',
    orgName: '华北大区',
    notSendNum: 0,
    parentorgId: null,
    projectAndMilestone: '',
    shopIncorrectNum: 12,
    targetNotEnoughNum: 8,
    totalRemindeNum: 2,
    remindNum: 1,
    regimentMonitorDetailList: [
        {
            orgId: '12123_01',
            chaheorgId: '12123_01',
            orgName: '北京',
            parentorgId: '12123',
            notSendNum: 0,
            projectAndMilestone: '项目及里程碑数据1',
            shopIncorrectNum: 12,
            targetNotEnoughNum: 8,
            totalRemindeNum: 2,
            remindNum: 1,
        },
        {
            orgId: '12123_01',
            caheorgId: '12123_01',
            orgName: '北京',
            parentorgId: '12123',
            notSendNum: 11,
            projectAndMilestone: '项目及里程碑数据2',
            shopIncorrectNum: 1,
            targetNotEnoughNum: 1,
            totalRemindeNum: 1,
            remindNum: 1,
        },
        // {
        //     orgId: '1212302',
        //     orgName: '天津',
        //     notSendNum: 0,
        //     shopIncorrectNum: 12,
        //     projectAndMilestone: '项目及里程碑数据',
        //     targetNotEnoughNum: 8,
        //     totalRemindeNum: 2,
        //     remindNum: 1,
        // },
        // {
        //     orgId: '1212303',
        //     orgName: '河北',
        //     notSendNum: 0,
        //     projectAndMilestone: '项目及里程碑数据',
        //     shopIncorrectNum: 12,
        //     targetNotEnoughNum: 8,
        //     totalRemindeNum: 2,
        //     remindNum: 1,
        // },
        // {
        //     orgId: '1212304',
        //     orgName: '石家庄',
        //     notSendNum: 0,
        //     projectAndMilestone: '项目及里程碑数据',
        //     shopIncorrectNum: 12,
        //     targetNotEnoughNum: 8,
        //     totalRemindeNum: 2,
        //     remindNum: 1,
        // },
    ]
},
    // {
    //     orgId: '12124',
    //     orgName: '华东大区',
    //     notSendNum: 0,
    //     projectAndMilestone: '项目及里程碑数据',
    //     shopIncorrectNum: 12,
    //     targetNotEnoughNum: 8,
    //     totalRemindeNum: 2,
    //     remindNum: 1,
    //     regimentMonitorDetailList: [
    //         {
    //             orgId: '1212401',
    //             orgName: '北京',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212402',
    //             orgName: '天津',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212403',
    //             orgName: '河北',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212404',
    //             orgName: '石家庄',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //     ]
    // },
    // {
    //     orgId: '12125',
    //     orgName: '华南大区',
    //     notSendNum: 0,
    //     projectAndMilestone: '项目及里程碑数据',
    //     shopIncorrectNum: 12,
    //     targetNotEnoughNum: 8,
    //     totalRemindeNum: 2,
    //     remindNum: 1,
    //     regimentMonitorDetailList: [
    //         {
    //             orgId: '1212501',
    //             orgName: '北京',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212502',
    //             orgName: '天津',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212503',
    //             orgName: '河北',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212504',
    //             orgName: '石家庄',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //     ]
    // },
    // {
    //     orgId: '12126',
    //     orgName: '华西大区',
    //     notSendNum: 0,
    //     projectAndMilestone: '项目及里程碑数据',
    //     shopIncorrectNum: 12,
    //     targetNotEnoughNum: 8,
    //     totalRemindeNum: 2,
    //     remindNum: 1,
    //     regimentMonitorDetailList: [
    //         {
    //             orgId: '1212601',
    //             orgName: '北京',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212602',
    //             orgName: '天津',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212603',
    //             orgName: '河北',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //         {
    //             orgId: '1212604',
    //             orgName: '石家庄',
    //             notSendNum: 0,
    //             projectAndMilestone: '项目及里程碑数据',
    //             shopIncorrectNum: 12,
    //             targetNotEnoughNum: 8,
    //             totalRemindeNum: 2,
    //             remindNum: 1,
    //         },
    //     ]
    // }
]